const DOM = {
  canvasContainer: document.getElementById("canvasContainer"),
  canvasWorkspace: document.getElementById("canvasWorkspace"),
  connectionsSvg: document.getElementById("connectionsSvg"),
  nodesLayer: document.getElementById("nodesLayer"),
  dragLineSvg: document.getElementById("dragLineSvg"),
  dragLinePath: document.getElementById("dragLinePath"),
  editorPanel: document.getElementById("editorPanel"),
  panelEmpty: document.getElementById("panelEmpty"),
  panelForm: document.getElementById("panelForm"),
  panelFooter: document.getElementById("panelFooter"),
  zoomLevel: document.getElementById("zoomLevel"),
  runtimeModal: document.getElementById("runtimeModal"),
  runtimeBody: document.getElementById("runtimeBody"),
  progressDots: document.getElementById("progressDots"),
  importModal: document.getElementById("importModal"),
  importDropzone: document.getElementById("importDropzone"),
  importFileInput: document.getElementById("importFileInput"),
  importTextarea: document.getElementById("importTextarea"),
  importError: document.getElementById("importError"),
  toastContainer: document.getElementById("toastContainer"),
  minimapCanvas: document.getElementById("minimapCanvas"),
  minimapViewport: document.getElementById("minimapViewport"),
};
