// Global application state
const state = {
  projects: [],
  activeProjectIndex: 0,
  maxUndo: 60,
  zoom: 1,
  panX: 0,
  panY: 0,
  isDraggingConnection: false,
  dragConnectionSource: null,
  dragConnectionMouse: { x: 0, y: 0 },
  isDraggingNode: false,
  dragNodeId: null,
  dragNodeOffset: { x: 0, y: 0 },
  dragNodeStartPos: { x: 0, y: 0 },
  isPanning: false,
  panStart: { x: 0, y: 0 },
  panStartOffset: { x: 0, y: 0 },
  runtimeActive: false,
  runtimeCurrentNodeId: null,
  runtimeHistory: [],
  runtimeVariables: {},
  saveTimeout: null,
  selectedNodeIds: new Set(),
  marquee: null,
  multiDragOffsets: null,
  runtimeStepLog: [],
  selectedConnection: null,
};
